# Generated by Django 4.1.5 on 2023-01-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0002_memory_placeurl"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memory",
            name="created",
        ),
    ]
