# Generated by Django 4.1.5 on 2023-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("memory", "0003_remove_memory_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memory",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="memory",
            name="image",
            field=models.ImageField(
                blank=True, default="media/default_image.jpeg", upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="placeAddress",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="memory",
            name="placeRoad",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="memory",
            name="placeUrl",
            field=models.TextField(blank=True, default=""),
        ),
    ]
