# Generated by Django 4.1.5 on 2023-01-26 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BucketList",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("bucket", models.TextField(default="")),
                ("isFinished", models.BooleanField(default=False)),
            ],
        ),
    ]
